# Document:
# http://simiki.org/docs/configuration.html

url: http://39.108.160.38
title: MC-WIKI
keywords: IT
description: record IT data
author: MC
deploy:
  - type: ftp
    host: 39.108.160.38
    port: 222
    user: root
    password: zhengming~138
